import { ethers, network } from "hardhat";
import * as fs from "fs";
import * as path from "path";

// Oracle Baby Jubjub public key — generated by: npx ts-node scripts/gen-oracle-key.ts
const ORACLE_PUBKEY_AX = process.env.ORACLE_PUBKEY_AX || "0";
const ORACLE_PUBKEY_AY = process.env.ORACLE_PUBKEY_AY || "0";
const USDC_ADDRESS = process.env.USDC_ADDRESS;
const FEE_TOKEN_ADDRESS = process.env.FEE_TOKEN_ADDRESS;

const SYNTH_ASSETS = [
  { name: "Confidential Synthetic Apple", symbol: "csAAPL", underlying: "AAPL" },
  { name: "Confidential Synthetic Tesla", symbol: "csTSLA", underlying: "TSLA" },
  { name: "Confidential Synthetic NVIDIA", symbol: "csNVDA", underlying: "NVDA" },
  { name: "Confidential Synthetic S&P 500", symbol: "csSPY", underlying: "SPY" },
  { name: "Confidential Synthetic Amazon", symbol: "csAMZN", underlying: "AMZN" },
  { name: "Confidential Synthetic Microsoft", symbol: "csMSFT", underlying: "MSFT" },
  { name: "Confidential Synthetic Meta", symbol: "csMETA", underlying: "META" },
  { name: "Confidential Synthetic Netflix", symbol: "csNFLX", underlying: "NFLX" },
  { name: "Confidential Synthetic AMD", symbol: "csAMD", underlying: "AMD" },
];

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("Deploying with:", deployer.address);
  console.log("Network:", network.name);
  console.log("Balance:", ethers.formatEther(await ethers.provider.getBalance(deployer.address)), "ETH\n");

  const isLocal = network.name === "hardhat" || network.name === "localhost";

  // ── 1. Underlying USDC ────────────────────────────────────────────────
  let underlyingUsdcAddress: string;
  if (isLocal) {
    console.log("1. Deploying MockUSDC...");
    const MockUSDC = await ethers.getContractFactory("MockUSDC");
    const mockUsdc = await MockUSDC.deploy();
    await mockUsdc.waitForDeployment();
    underlyingUsdcAddress = await mockUsdc.getAddress();
    console.log("   MockUSDC:", underlyingUsdcAddress);
  } else {
    if (!USDC_ADDRESS) {
      throw new Error("Set USDC_ADDRESS in contracts/.env for live deployments");
    }
    underlyingUsdcAddress = USDC_ADDRESS;
    console.log("1. Using USDC:", underlyingUsdcAddress);
  }

  // ── 2. Fee token (optional) ────────────────────────────────────────────
  let feeTokenAddress: string | undefined;
  if (isLocal) {
    console.log("2. Deploying MockFeeToken (MockHSP)...");
    const MockHSP = await ethers.getContractFactory("MockHSP");
    const feeToken = await MockHSP.deploy();
    await feeToken.waitForDeployment();
    feeTokenAddress = await feeToken.getAddress();
    console.log("   MockFeeToken:", feeTokenAddress);
  } else if (FEE_TOKEN_ADDRESS) {
    feeTokenAddress = FEE_TOKEN_ADDRESS;
    console.log("2. Using fee token:", feeTokenAddress);
  } else {
    console.log("2. Fee token not set; fee module will be disabled.");
  }

  // ── 3. ConfidentialTierManager (deploy FIRST, needed by ZKVerifier) ────
  console.log("3. Deploying ConfidentialTierManager...");
  const TierManager = await ethers.getContractFactory("ConfidentialTierManager");
  const tierManager = await TierManager.deploy();
  await tierManager.waitForDeployment();
  const tierManagerAddress = await tierManager.getAddress();
  console.log("   ConfidentialTierManager:", tierManagerAddress);

  // ── 4. Groth16Verifier + ZKVerifier ─────────────────────────────────────
  let zkVerifierAddress: string;
  if (isLocal) {
    console.log("4. Deploying MockZKVerifier (local)...");
    const MockZKVerifier = await ethers.getContractFactory("MockZKVerifier");
    const mockZKVerifier = await MockZKVerifier.deploy();
    await mockZKVerifier.waitForDeployment();
    zkVerifierAddress = await mockZKVerifier.getAddress();
    console.log("   MockZKVerifier:", zkVerifierAddress);
  } else {
    if (ORACLE_PUBKEY_AX === "0" || ORACLE_PUBKEY_AY === "0") {
      throw new Error(
        "Set ORACLE_PUBKEY_AX and ORACLE_PUBKEY_AY in contracts/.env\n" +
        "Run: npx ts-node scripts/gen-oracle-key.ts to generate a keypair"
      );
    }
    console.log("4. Deploying Groth16Verifier...");
    const Groth16Verifier = await ethers.getContractFactory("Groth16Verifier");
    const groth16Verifier = await Groth16Verifier.deploy();
    await groth16Verifier.waitForDeployment();
    const groth16VerifierAddress = await groth16Verifier.getAddress();
    console.log("   Groth16Verifier:", groth16VerifierAddress);

    console.log("4b. Deploying ZKVerifier with oracle public key...");
    console.log("    Oracle Ax:", ORACLE_PUBKEY_AX.slice(0, 20) + "...");
    const ZKVerifier = await ethers.getContractFactory("ZKVerifier");
    const zkVerifier = await ZKVerifier.deploy(
      groth16VerifierAddress,
      tierManagerAddress,
      BigInt(ORACLE_PUBKEY_AX),
      BigInt(ORACLE_PUBKEY_AY)
    );
    await zkVerifier.waitForDeployment();
    zkVerifierAddress = await zkVerifier.getAddress();
    console.log("   ZKVerifier:", zkVerifierAddress);
  }

  // ── 5. ConfidentialUSDC (cUSDC) ─────────────────────────────────────────
  console.log("5. Deploying ConfidentialUSDC...");
  const ConfidentialUSDC = await ethers.getContractFactory("ConfidentialUSDC");
  const cUSDC = await ConfidentialUSDC.deploy(underlyingUsdcAddress);
  await cUSDC.waitForDeployment();
  const cUSDCAddress = await cUSDC.getAddress();
  console.log("   ConfidentialUSDC:", cUSDCAddress);

  // ── 6. Confidential SynthTokens ─────────────────────────────────────────
  console.log("6. Deploying ConfidentialSynthTokens...");
  const ConfidentialSynthToken = await ethers.getContractFactory("ConfidentialSynthToken");
  const synthTokens: { symbol: string; address: string; contract: any }[] = [];
  for (const asset of SYNTH_ASSETS) {
    const token = await ConfidentialSynthToken.deploy(
      deployer.address,
      asset.name,
      asset.symbol,
      asset.underlying,
      `https://ztocks.io/tokens/${asset.symbol.toLowerCase()}`
    );
    await token.waitForDeployment();
    const tokenAddress = await token.getAddress();
    synthTokens.push({ symbol: asset.symbol, address: tokenAddress, contract: token });
    console.log(`   ${asset.symbol}:`, tokenAddress);
  }

  // ── 7. FeeModule (optional) ─────────────────────────────────────────────
  let feeModuleAddress = ethers.ZeroAddress;
  let feeModule: any = undefined;
  if (feeTokenAddress) {
    console.log("7. Deploying FeeModule...");
    const FeeModule = await ethers.getContractFactory("FeeModule");
    feeModule = await FeeModule.deploy(feeTokenAddress, deployer.address);
    await feeModule.waitForDeployment();
    feeModuleAddress = await feeModule.getAddress();
    console.log("   FeeModule:", feeModuleAddress);
  } else {
    console.log("7. FeeModule skipped.");
  }

  // ── 8. ConfidentialSynthVaultFHE ────────────────────────────────────────
  console.log("8. Deploying ConfidentialSynthVaultFHE...");
  const SynthVault = await ethers.getContractFactory("ConfidentialSynthVaultFHE");
  const vault = await SynthVault.deploy(
    zkVerifierAddress,
    tierManagerAddress,
    cUSDCAddress,
    feeModuleAddress
  );
  await vault.waitForDeployment();
  console.log("   ConfidentialSynthVaultFHE:", await vault.getAddress());

  // ── 9. Wire up permissions ──────────────────────────────────────────────
  console.log("\n9. Wiring up permissions...");
  const vaultAddr = await vault.getAddress();

  // Set vault on each SynthToken
  for (const token of synthTokens) {
    await (await token.contract.setVault(vaultAddr)).wait();
  }
  console.log("    ConfidentialSynthToken.setVault ✓");

  // Set vault on fee module (if deployed)
  if (feeModule && feeModuleAddress !== ethers.ZeroAddress) {
    await (await feeModule.setVault(vaultAddr)).wait();
    console.log("    FeeModule.setVault ✓");
  }

  // Register synth assets on vault
  for (const token of synthTokens) {
    await (await vault.registerSynthAsset(token.address)).wait();
  }
  console.log("    vault.registerSynthAsset ✓");

  // ── 10. Save deployment addresses ───────────────────────────────────────
  const deployments = {
    network:               network.name,
    deployedAt:            new Date().toISOString(),
    deployer:              deployer.address,
    underlyingUSDC:        underlyingUsdcAddress,
    ConfidentialUSDC:      cUSDCAddress,
    ZKVerifier:            zkVerifierAddress,
    ConfidentialTierManager: tierManagerAddress,
    ConfidentialSynthVaultFHE: await vault.getAddress(),
    FeeModule:             feeModuleAddress === ethers.ZeroAddress ? undefined : feeModuleAddress,
    FeeToken:              feeTokenAddress,
    tokens: Object.fromEntries(synthTokens.map((token) => [token.symbol, token.address])),
  };

  const outDir = path.join(__dirname, "..", "deployments");
  if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });
  const outFile = path.join(outDir, `${network.name}.json`);
  fs.writeFileSync(outFile, JSON.stringify(deployments, null, 2));
  console.log(`\n✓ Deployment saved to ${outFile}`);

  // ── 11. Print .env values ──────────────────────────────────────────────
  console.log("\n─── Copy these to your .env / Vercel env vars ─────────────────");
  console.log(`NEXT_PUBLIC_USDC_ADDRESS=${underlyingUsdcAddress}`);
  console.log(`NEXT_PUBLIC_CUSDC_ADDRESS=${cUSDCAddress}`);
  if (feeTokenAddress) {
    console.log(`NEXT_PUBLIC_FEE_TOKEN_ADDRESS=${feeTokenAddress}`);
  }
  console.log(`NEXT_PUBLIC_ZK_VERIFIER_ADDRESS=${zkVerifierAddress}`);
  console.log(`NEXT_PUBLIC_TIER_MANAGER_ADDRESS=${tierManagerAddress}`);
  console.log(`NEXT_PUBLIC_SYNTH_VAULT_ADDRESS=${await vault.getAddress()}`);
  if (feeModuleAddress !== ethers.ZeroAddress) {
    console.log(`NEXT_PUBLIC_FEE_MODULE_ADDRESS=${feeModuleAddress}`);
  }
  for (const token of synthTokens) {
    const envKey = `NEXT_PUBLIC_${token.symbol.toUpperCase()}_ADDRESS`;
    console.log(`${envKey}=${token.address}`);
  }
  console.log("────────────────────────────────────────────────────────────\n");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
