import { ethers, network } from "hardhat";
import * as fs from "fs";
import * as path from "path";

// Oracle Baby Jubjub public key — generated by: npx ts-node scripts/gen-oracle-key.ts
const ORACLE_PUBKEY_AX = process.env.ORACLE_PUBKEY_AX || "0";
const ORACLE_PUBKEY_AY = process.env.ORACLE_PUBKEY_AY || "0";

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("Deploying with:", deployer.address);
  console.log("Network:", network.name);
  console.log("Balance:", ethers.formatEther(await ethers.provider.getBalance(deployer.address)), "ETH\n");

  const isLocal = network.name === "hardhat" || network.name === "localhost";

  // ── 1. MockUSDC ─────────────────────────────────────────────────────────
  console.log("1. Deploying MockUSDC...");
  const MockUSDC = await ethers.getContractFactory("MockUSDC");
  const usdc = await MockUSDC.deploy();
  await usdc.waitForDeployment();
  console.log("   MockUSDC:", await usdc.getAddress());

  // ── 2. MockFeeToken ─────────────────────────────────────────────────────
  console.log("2. Deploying MockFeeToken (MockHSP)...");
  const MockHSP = await ethers.getContractFactory("MockHSP");
  const feeToken = await MockHSP.deploy();
  await feeToken.waitForDeployment();
  console.log("   MockFeeToken:", await feeToken.getAddress());

  // ── 3. Groth16Verifier + ZKVerifier ─────────────────────────────────────
  let zkVerifierAddress: string;
  if (isLocal) {
    console.log("3. Deploying MockZKVerifier (local)...");
    const MockZKVerifier = await ethers.getContractFactory("MockZKVerifier");
    const mockZKVerifier = await MockZKVerifier.deploy();
    await mockZKVerifier.waitForDeployment();
    zkVerifierAddress = await mockZKVerifier.getAddress();
    console.log("   MockZKVerifier:", zkVerifierAddress);
  } else {
    if (ORACLE_PUBKEY_AX === "0" || ORACLE_PUBKEY_AY === "0") {
      throw new Error(
        "Set ORACLE_PUBKEY_AX and ORACLE_PUBKEY_AY in contracts/.env\n" +
        "Run: npx ts-node scripts/gen-oracle-key.ts to generate a keypair"
      );
    }
    console.log("3. Deploying Groth16Verifier...");
    const Groth16Verifier = await ethers.getContractFactory("Groth16Verifier");
    const groth16Verifier = await Groth16Verifier.deploy();
    await groth16Verifier.waitForDeployment();
    const groth16VerifierAddress = await groth16Verifier.getAddress();
    console.log("   Groth16Verifier:", groth16VerifierAddress);

    console.log("3b. Deploying ZKVerifier with oracle public key...");
    console.log("    Oracle Ax:", ORACLE_PUBKEY_AX.slice(0, 20) + "...");
    const ZKVerifier = await ethers.getContractFactory("ZKVerifier");
    const zkVerifier = await (ZKVerifier as any).deploy(
      groth16VerifierAddress,
      BigInt(ORACLE_PUBKEY_AX),
      BigInt(ORACLE_PUBKEY_AY)
    );
    await zkVerifier.waitForDeployment();
    zkVerifierAddress = await zkVerifier.getAddress();
    console.log("   ZKVerifier:", zkVerifierAddress);
  }

  // ── 4. ConfidentialTierManager ──────────────────────────────────────────
  console.log("4. Deploying ConfidentialTierManager...");
  const TierManager = await ethers.getContractFactory("ConfidentialTierManager");
  const tierManager = await TierManager.deploy();
  await tierManager.waitForDeployment();
  const tierManagerAddress = await tierManager.getAddress();
  console.log("    ConfidentialTierManager:", tierManagerAddress);

  // ── 5. SynthTokens ─────────────────────────────────────────────────────
  console.log("5. Deploying SynthTokens...");
  const SynthToken = await ethers.getContractFactory("SynthToken");
  const sAAPL = await SynthToken.deploy("Synthetic Apple",     "sAAPL", "AAPL");
  const sTSLA = await SynthToken.deploy("Synthetic Tesla",     "sTSLA", "TSLA");
  const sNVDA = await SynthToken.deploy("Synthetic NVIDIA",    "sNVDA", "NVDA");
  const sSPY  = await SynthToken.deploy("Synthetic S&P 500",   "sSPY",  "SPY");
  const sAMZN = await SynthToken.deploy("Synthetic Amazon",    "sAMZN", "AMZN");
  const sMSFT = await SynthToken.deploy("Synthetic Microsoft", "sMSFT", "MSFT");
  const sMETA = await SynthToken.deploy("Synthetic Meta",      "sMETA", "META");
  const sNFLX = await SynthToken.deploy("Synthetic Netflix",   "sNFLX", "NFLX");
  const sAMD  = await SynthToken.deploy("Synthetic AMD",       "sAMD",  "AMD");
  await Promise.all([
    sAAPL.waitForDeployment(), sTSLA.waitForDeployment(),
    sNVDA.waitForDeployment(), sSPY.waitForDeployment(),
    sAMZN.waitForDeployment(), sMSFT.waitForDeployment(),
    sMETA.waitForDeployment(), sNFLX.waitForDeployment(),
    sAMD.waitForDeployment(),
  ]);
  console.log("   sAAPL:", await sAAPL.getAddress());
  console.log("   sTSLA:", await sTSLA.getAddress());
  console.log("   sNVDA:", await sNVDA.getAddress());
  console.log("   sSPY: ", await sSPY.getAddress());
  console.log("   sAMZN:", await sAMZN.getAddress());
  console.log("   sMSFT:", await sMSFT.getAddress());
  console.log("   sMETA:", await sMETA.getAddress());
  console.log("   sNFLX:", await sNFLX.getAddress());
  console.log("   sAMD: ", await sAMD.getAddress());

  // ── 6. FeeModule ────────────────────────────────────────────────────────
  console.log("6. Deploying FeeModule...");
  const FeeModule = await ethers.getContractFactory("FeeModule");
  const feeModule = await FeeModule.deploy(
    await feeToken.getAddress(),
    deployer.address
  );
  await feeModule.waitForDeployment();
  console.log("   FeeModule:", await feeModule.getAddress());

  // ── 7. ConfidentialSynthVault ───────────────────────────────────────────
  console.log("7. Deploying ConfidentialSynthVault...");
  const SynthVault = await ethers.getContractFactory("ConfidentialSynthVault");
  const vault = await SynthVault.deploy(
    zkVerifierAddress,
    tierManagerAddress,
    await usdc.getAddress(),
    await feeModule.getAddress()
  );
  await vault.waitForDeployment();
  console.log("   ConfidentialSynthVault:", await vault.getAddress());

  // ── 8. Wire up permissions ──────────────────────────────────────────────
  console.log("\n8. Wiring up permissions...");
  const vaultAddr = await vault.getAddress();

  // Set vault on each SynthToken
  const synthTokens = [sAAPL, sTSLA, sNVDA, sSPY, sAMZN, sMSFT, sMETA, sNFLX, sAMD];
  for (const token of synthTokens) {
    await (await token.setVault(vaultAddr)).wait();
  }
  console.log("    SynthToken.setVault ✓");

  // Set vault on fee module
  await (await feeModule.setVault(vaultAddr)).wait();
  console.log("    FeeModule.setVault ✓");

  // Register synth assets on vault
  for (const token of synthTokens) {
    await (await vault.registerSynthAsset(await token.getAddress())).wait();
  }
  console.log("    vault.registerSynthAsset ✓");

  // Seed vault payout liquidity
  const vaultSeedUSDC = 1_000n * 10n ** 6n;
  await (await usdc.faucet(vaultAddr, vaultSeedUSDC)).wait();
  console.log("    vault USDC liquidity seeded ✓", Number(vaultSeedUSDC) / 1e6, "USDC");

  // ── 9. Save deployment addresses ────────────────────────────────────────
  const deployments = {
    network:               network.name,
    deployedAt:            new Date().toISOString(),
    deployer:              deployer.address,
    MockUSDC:              await usdc.getAddress(),
    MockFeeToken:          await feeToken.getAddress(),
    ZKVerifier:            zkVerifierAddress,
    ConfidentialTierManager: tierManagerAddress,
    ConfidentialSynthVault: await vault.getAddress(),
    FeeModule:             await feeModule.getAddress(),
    tokens: {
      sAAPL: await sAAPL.getAddress(),
      sTSLA: await sTSLA.getAddress(),
      sNVDA: await sNVDA.getAddress(),
      sSPY:  await sSPY.getAddress(),
      sAMZN: await sAMZN.getAddress(),
      sMSFT: await sMSFT.getAddress(),
      sMETA: await sMETA.getAddress(),
      sNFLX: await sNFLX.getAddress(),
      sAMD:  await sAMD.getAddress(),
    },
  };

  const outDir = path.join(__dirname, "..", "deployments");
  if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });
  const outFile = path.join(outDir, `${network.name}.json`);
  fs.writeFileSync(outFile, JSON.stringify(deployments, null, 2));
  console.log(`\n✓ Deployment saved to ${outFile}`);

  // ── 10. Print .env values ──────────────────────────────────────────────
  console.log("\n─── Copy these to your .env / Vercel env vars ─────────────────");
  console.log(`NEXT_PUBLIC_USDC_ADDRESS=${await usdc.getAddress()}`);
  console.log(`NEXT_PUBLIC_FEE_TOKEN_ADDRESS=${await feeToken.getAddress()}`);
  console.log(`NEXT_PUBLIC_ZK_VERIFIER_ADDRESS=${zkVerifierAddress}`);
  console.log(`NEXT_PUBLIC_TIER_MANAGER_ADDRESS=${tierManagerAddress}`);
  console.log(`NEXT_PUBLIC_SYNTH_VAULT_ADDRESS=${await vault.getAddress()}`);
  console.log(`NEXT_PUBLIC_FEE_MODULE_ADDRESS=${await feeModule.getAddress()}`);
  console.log(`NEXT_PUBLIC_SAAPL_ADDRESS=${await sAAPL.getAddress()}`);
  console.log(`NEXT_PUBLIC_STSLA_ADDRESS=${await sTSLA.getAddress()}`);
  console.log(`NEXT_PUBLIC_SNVDA_ADDRESS=${await sNVDA.getAddress()}`);
  console.log(`NEXT_PUBLIC_SSPY_ADDRESS=${await sSPY.getAddress()}`);
  console.log(`NEXT_PUBLIC_SAMZN_ADDRESS=${await sAMZN.getAddress()}`);
  console.log(`NEXT_PUBLIC_SMSFT_ADDRESS=${await sMSFT.getAddress()}`);
  console.log(`NEXT_PUBLIC_SMETA_ADDRESS=${await sMETA.getAddress()}`);
  console.log(`NEXT_PUBLIC_SNFLX_ADDRESS=${await sNFLX.getAddress()}`);
  console.log(`NEXT_PUBLIC_SAMD_ADDRESS=${await sAMD.getAddress()}`);
  console.log("────────────────────────────────────────────────────────────\n");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
