// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/access/Ownable.sol";
import "./Groth16Verifier.sol";
import "./ConfidentialTierManager.sol";

/// @title ZKVerifier
/// @notice Verifies Groth16 ZK proofs (generated by Circom + snarkjs) to register
///         a wallet's KYC tier on-chain. The tier is then encrypted and stored in
///         ConfidentialTierManager. Only the tier number is stored — no personal
///         data (name, DOB, nationality) ever touches the chain.
///         The oracle credential message now includes a private creditScore that is
///         constrained in-circuit to the submitted tier band.
///
/// @dev Circuit: circuits/tier_proof.circom
///      Public signals layout (indices into pubSignals[6]):
///        [0] nullifier      — Poseidon(nonce, walletAddr), anti-replay
///        [1] tierPub        — KYC tier 1-4 committed by proof
///        [2] expiryPub      — credential expiry (unix timestamp)
///        [3] walletAddrPub  — wallet address as uint160
///        [4] Ax             — oracle Baby Jubjub public key X
///        [5] Ay             — oracle Baby Jubjub public key Y
contract ZKVerifier is Ownable {

    // ─── State ────────────────────────────────────────────────────────────────
    Groth16Verifier public immutable verifier;
    ConfidentialTierManager public immutable tierManager;

    /// @notice Oracle's Baby Jubjub public key — must match the key that signed
    ///         the credential in POST /api/kyc/issue. Set at deployment.
    uint256 public immutable ORACLE_AX;
    uint256 public immutable ORACLE_AY;

    /// @notice Verified KYC tier per user wallet (1–4). 0 = not verified.
    mapping(address => uint8) public userTier;

    /// @notice Timestamp when the user's credential expires.
    mapping(address => uint256) public userProofExpiry;

    /// @notice Nullifiers already used — prevents proof replay attacks.
    mapping(uint256 => bool) public usedNullifiers;

    // ─── Events ───────────────────────────────────────────────────────────────
    event TierVerified(address indexed user, uint8 tier, uint256 expiry);

    // ─── Errors ───────────────────────────────────────────────────────────────
    error NullifierAlreadyUsed(uint256 nullifier);
    error WrongOracleKey(uint256 gotAx, uint256 gotAy);
    error ProofNotForSender(uint256 proofAddr, address sender);
    error CredentialExpired(uint256 expiry);
    error InvalidTier(uint256 tier);
    error InvalidProof();

    // ─── Constructor ──────────────────────────────────────────────────────────
    constructor(
        address _verifier,
        address _tierManager,
        uint256 _oracleAx,
        uint256 _oracleAy
    ) Ownable(msg.sender) {
        require(_verifier != address(0), "ZKVerifier: zero verifier");
        require(_tierManager != address(0), "ZKVerifier: zero tierManager");
        verifier  = Groth16Verifier(_verifier);
        tierManager = ConfidentialTierManager(_tierManager);
        ORACLE_AX = _oracleAx;
        ORACLE_AY = _oracleAy;
    }

    // ─── Core: Submit Proof ───────────────────────────────────────────────────

    /// @notice Submit a Groth16 proof to register your KYC tier on-chain.
    /// @param  a, b, c   Groth16 proof components (from snarkjs calldata).
    /// @param  pubSignals The 6 public signals from the tier_proof circuit.
    function submitProof(
        uint[2]    calldata a,
        uint[2][2] calldata b,
        uint[2]    calldata c,
        uint[6]    calldata pubSignals
    ) external {
        uint256 nullifier     = pubSignals[0];
        uint256 tierPub       = pubSignals[1];
        uint256 expiryPub     = pubSignals[2];
        uint256 walletAddrPub = pubSignals[3];
        uint256 ax            = pubSignals[4];
        uint256 ay            = pubSignals[5];

        // 1. Anti-replay: each nullifier can only be used once
        if (usedNullifiers[nullifier]) revert NullifierAlreadyUsed(nullifier);

        // 2. Proof must have been signed by our oracle's key
        if (ax != ORACLE_AX || ay != ORACLE_AY) revert WrongOracleKey(ax, ay);

        // 3. Proof must be for the calling wallet
        if (uint160(walletAddrPub) != uint160(msg.sender))
            revert ProofNotForSender(walletAddrPub, msg.sender);

        // 4. Credential must not be expired
        if (block.timestamp > expiryPub) revert CredentialExpired(expiryPub);

        // 5. Tier must be in valid range
        if (tierPub == 0 || tierPub > 4) revert InvalidTier(tierPub);

        // 6. Verify the Groth16 proof on-chain
        if (!verifier.verifyProof(a, b, c, pubSignals)) revert InvalidProof();

        // 7. Store — only tier + expiry, zero personal data
        usedNullifiers[nullifier]   = true;
        userTier[msg.sender]        = uint8(tierPub);
        userProofExpiry[msg.sender] = expiryPub;

        // 8. Set encrypted tier in TierManager
        tierManager.setTier(msg.sender, uint8(tierPub));

        emit TierVerified(msg.sender, uint8(tierPub), expiryPub);
    }

    // ─── Views ────────────────────────────────────────────────────────────────

    /// @notice Returns true if user has a valid, non-expired ZK proof on file.
    function isVerified(address user) external view returns (bool) {
        return userTier[user] > 0 && block.timestamp <= userProofExpiry[user];
    }

    /// @notice Returns user's stored tier and proof expiry timestamp.
    function getTier(address user) external view returns (uint8 tier, uint256 expiry) {
        return (userTier[user], userProofExpiry[user]);
    }
}
